using System;
using System.Collections.Generic;
using Manifold.Internal.Util;
using Vintagestory.API.Server;

namespace Manifold.Internal;

/// <summary>
/// Drives streaming worldgen: on a periodic server tick, gathers online players in streaming
/// dimensions, asks <see cref="StreamingPlanner"/> which columns to ensure (budget-capped,
/// nearest-first), then generates/loads and force-sends them (no server relight).
/// </summary>
/// <remarks>Server-side, main thread. Logic lives in <see cref="StreamingPlanner"/>; this is glue.</remarks>
internal sealed class StreamingWorldgenDriver
{
    private const int TickIntervalMs = 250;

    private readonly ICoreServerAPI _sapi;
    private readonly DimensionRegistry _registry;
    private readonly DimensionGenerator _generator;

    private long _listenerId = -1;

    /// <summary>Initializes a new instance of the <see cref="StreamingWorldgenDriver"/> class.</summary>
    /// <param name="sapi">Server API.</param>
    /// <param name="registry">Dimension registry (to find streaming dimensions).</param>
    /// <param name="generator">Generator used to ensure individual columns.</param>
    public StreamingWorldgenDriver(ICoreServerAPI sapi, DimensionRegistry registry, DimensionGenerator generator)
    {
        _sapi = sapi ?? throw new ArgumentNullException(nameof(sapi));
        _registry = registry ?? throw new ArgumentNullException(nameof(registry));
        _generator = generator ?? throw new ArgumentNullException(nameof(generator));
    }

    /// <summary>Registers the periodic tick listener.</summary>
    public void Start() => _listenerId = _sapi.Event.RegisterGameTickListener(OnTick, TickIntervalMs);

    /// <summary>Unregisters the tick listener.</summary>
    public void Stop()
    {
        if (_listenerId >= 0)
        {
            _sapi.Event.UnregisterGameTickListener(_listenerId);
            _listenerId = -1;
        }
    }

    private void OnTick(float dt)
    {
        var players = GatherStreamingPlayers(out var byUid);
        if (players.Count == 0)
        {
            return;
        }

        var planned = StreamingPlanner.Plan(players, IsColumnLoaded, BudgetForDim);
        if (planned.Count == 0)
        {
            return;
        }

        // Generate (or load) each planned column and force-send it to the players streaming it.
        // No server relight: see DimensionGenerator.EnsureRegion for why (it would flood skylight
        // and override the client's own lighting).
        foreach (var col in planned)
        {
            _generator.EnsureColumn(_sapi, col.DimId, col.Cx, col.Cz);

            foreach (var uid in col.PlayerUids)
            {
                if (byUid.TryGetValue(uid, out var player))
                {
                    _sapi.WorldManager.ForceSendChunkColumn(player, col.Cx, col.Cz, col.DimId);
                }
            }
        }
    }

    /// <summary>Builds the planner input from online players currently in streaming dimensions.</summary>
    private List<StreamingPlayer> GatherStreamingPlayers(out Dictionary<string, IServerPlayer> byUid)
    {
        var result = new List<StreamingPlayer>();
        byUid = new Dictionary<string, IServerPlayer>();

        foreach (var player in _sapi.World.AllOnlinePlayers)
        {
            if (player is not IServerPlayer sp || EntityPosAccess.PosOrNull(sp.Entity) is not { } pos)
            {
                continue;
            }

            int dimId = pos.Dimension;
            var dim = _registry.GetByInternalId(dimId);
            if (dim?.StreamingLoadRadius is not { } dimRadius)
            {
                continue;
            }

            // The configured loadRadius is a floor; the window follows the radius the engine sends
            // to this player (their own view distance, capped by the server's), read each tick so a
            // change of either is picked up. MaxChunkRadius is not constant: the engine raises it
            // when a singleplayer client asks for a larger view distance.
            int radius = StreamingPlanner.WindowRadius(
                dimRadius,
                sp.WorldData?.LastApprovedViewDistance ?? 0,
                _sapi.Server.Config.MaxChunkRadius);

            int cx = ChunkMath.ToChunk(pos.X);
            int cz = ChunkMath.ToChunk(pos.Z);
            result.Add(new StreamingPlayer(sp.PlayerUID, dimId, cx, cz, radius));
            byUid[sp.PlayerUID] = sp;
        }

        return result;
    }

    /// <summary>
    /// Whether the planner can skip a column: generated by Manifold for this dimension and in
    /// memory. A column that is only in memory is a leftover of a destroyed dimension whose engine
    /// id was recycled (see <see cref="DimensionGenerator.IsColumnReady"/>) and must be generated.
    /// </summary>
    private bool IsColumnLoaded(int dimId, int cx, int cz) => _generator.IsColumnReady(_sapi, dimId, cx, cz);

    /// <summary>
    /// Resolves the per-tick column budget for a dimension: dim-specific setting if configured,
    /// otherwise the default. Falls back to the default when the dim is not in the registry
    /// (defensive: in practice we only ask for streaming dims, which are all known).
    /// </summary>
    private int BudgetForDim(int dimId) =>
        _registry.GetByInternalId(dimId)?.StreamingBudgetPerTick
            ?? DimensionBuilderImpl.DefaultStreamingBudgetPerTick;
}
