apiRules:
- include:
    uidRegex: ^Manifold\.Api
    type: Namespace
- include:
    uidRegex: ^Manifold\.Api
    type: Type
- include:
    uidRegex: ^Manifold\.Api
    type: Member
- exclude:
    uidRegex: ^Manifold\.Internal
    type: Namespace
- exclude:
    uidRegex: ^Manifold\.Internal
